---
- name: linuxコマンド実行通知
  hosts: linux
  gather_facts: no
  become: yes
  vars:
    my_command: "df -h"
  pre_tasks:
    
    - name: 現在日時取得
      shell: date +%Y%m%d%H%M
      register: res_date

    - set_fact:
        my_date: "{{ res_date.stdout }}" 

    - name: コマンド実行
      shell: "{{ my_command }}"
      register: res
      changed_when: no
    
    - name: 実行結果出力
      debug:
        var=res.stdout_lines

    - name: ファイル出力
      copy:
        content: "{{ res.stdout }}"
        dest: "/tmp/ansible_command_result_{{ my_date }}.txt"

    - name: ファイル取得
      fetch:
        src: "/tmp/ansible_command_result_{{ my_date }}.txt"
        dest: "/tmp/ansible_command_result_{{ my_date }}.txt"
        flat: yes
