---
- name: Webサーバセットアップ
  hosts: all
  tasks:
    - name: Apacheインストール
      package:
        name: 
          - httpd 
          - mod_ssl
        state: present

    - name: コンテンツの配信 
      copy:
        src: ./files/index.html
        dest: /var/www/html/index.html
        owner: ibmstudent
        
    - name: Apache起動
      service:
        state: started
        name: httpd
